name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [1.16, 1.18, 1.20]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - 
        name: Run tests
        run: |
          go test ./... -test.v