name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [1.16.x, 1.18.x, 1.20.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - 
        name: Install dependencies
        run: go get .
      - 
        name: Run tests
        run: go test . -test.v